apiVersion: 1

datasources:
  # Prometheus data source pointing to the Prometheus container
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
